[package]
name = "protoevo-render"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
bevy = { workspace = true }
bevy_rapier2d = { workspace = true }
log = { workspace = true }
rand = { workspace = true }

# Internal dependencies
protoevo-core = { path = "../protoevo-core" }
protoevo-compute = { path = "../protoevo-compute" }
